# Generated by Django 3.0.3 on 2020-02-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubby', '0002_club_event_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='atendees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, help_text='The ticket price for your event, 0 if free.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubby.Club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('c', 'casual'), ('f', 'fancy'), ('d', 'dress_up'), ('p', 'private')], default='m', help_text='event type', max_length=1),
        ),
    ]
