# Generated by Django 3.0.3 on 2020-03-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0007_auto_20200309_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_user', 'Is a user and can do everything an identified user can.'), ('is_owner', 'Is an owner and can do everything an identified owner can.'), ('is_premium_owner', 'Is an owner and can do everything an identified owner can.'))},
        ),
    ]
