# Generated by Django 3.0.3 on 2020-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0010_auto_20200311_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=12, help_text='event duration in hours, max is 12 hours', max_length=2),
        ),
    ]
