# Generated by Django 3.0.4 on 2020-03-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0016_auto_20200312_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qr_item',
            name='order',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
