# Generated by Django 3.0.3 on 2020-03-24 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0005_auto_20200324_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('reservation_exclusive', 'product_type')},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('category', 'price')},
        ),
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.URLField(blank=True, help_text='URL to a picture of your club', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.URLField(blank=True, help_text='URL to the poster for the event', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, help_text='Post a picture of your pretty face, dude', null=True),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 16, 57, 22, 309483)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 16, 57, 22, 309483)),
        ),
    ]
