# Generated by Django 3.0.3 on 2020-03-09 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubby', '0006_auto_20200303_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flavour', models.CharField(max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('stars', models.IntegerField(help_text='star rating 1-10')),
                ('recommended', models.BooleanField(help_text='would you recommend this club?')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('hookah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Hookah')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('c', 'casual'), ('f', 'fancy'), ('d', 'dress_up'), ('p', 'private')], default='c', help_text='event type', max_length=1),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Event'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubby.Reservation'),
        ),
    ]
