# Generated by Django 3.0.3 on 2020-03-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0008_auto_20200309_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_user', 'Is a user and can do everything an identified user can.'), ('is_owner', 'Is an owner and can do everything an identified owner can.'), ('is_premium_owner', 'Is a premium owner and can do everything an identified owner can and more.'))},
        ),
    ]
