# Generated by Django 3.0.4 on 2020-03-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0008_auto_20200328_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='max_capacity',
            field=models.PositiveIntegerField(help_text="The capacity of your club, you're responsible for the enforcement of this number."),
        ),
        migrations.AlterField(
            model_name='createticket',
            name='description',
            field=models.TextField(default='this allows you to enter the party.', help_text='Decribe what this ticket entices.', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=12, help_text='event duration in hours, max is 12 hours', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.PositiveIntegerField(default=12, help_text='event start time 24h format.', max_length=2),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 12, 23, 11, 314697)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 12, 23, 11, 312672)),
        ),
    ]
