# Generated by Django 3.0.3 on 2020-03-29 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0009_auto_20200329_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[(12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0, help_text='event duration in hours, max is 12 hours.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('rock', 'rock'), ('pop', 'pop'), ('techno', 'techno'), ('hip hop', 'hip hop'), ('trap', 'trap'), ('reggaeton', 'reggaeton'), ('indie', 'indie'), ('metal', 'metal'), ('latino', 'latino')], default='reggaeton', help_text='event music type', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (23, 23), (22, 22), (21, 21), (20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0, help_text='event start time 24h format.'),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 14, 56, 17, 230519)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 14, 56, 17, 230519)),
        ),
    ]
