# Generated by Django 3.0.4 on 2020-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0017_auto_20200313_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=(0.0), max_digits=5),
            preserve_default=False,
        ),
    ]
