# Generated by Django 3.0.3 on 2020-04-09 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0018_auto_20200408_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_username',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 23, 36, 47, 52906)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 23, 36, 47, 52906)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 23, 36, 47, 51906)),
        ),
        migrations.AlterField(
            model_name='securityadvice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 23, 36, 47, 51906)),
        ),
    ]
