# Generated by Django 3.0.3 on 2020-04-10 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0019_auto_20200409_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 2, 15, 864501)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 2, 15, 864501)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 2, 15, 863501)),
        ),
        migrations.AlterField(
            model_name='securityadvice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 2, 15, 864501)),
        ),
    ]
