# Generated by Django 3.0.3 on 2020-03-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0020_auto_20200313_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubby.Product'),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubby.Reservation'),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubby.Ticket'),
        ),
    ]
