# Generated by Django 3.0.3 on 2020-03-15 17:53

import clubby.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubby', '0021_auto_20200314_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(default='Basic', help_text='The name of the type of ticket you are trying to sell.', max_length=40)),
                ('description', models.TextField(default='this allows you to enter the party.', help_text='Decribe what this ticket entices.')),
                ('size', clubby.models.IntegerRangeField(default=1, help_text='Number of tickets. (Max)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubby.Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
