# Generated by Django 3.0.3 on 2020-04-10 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0021_auto_20200410_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_expiration_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 44, 49, 99306)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 44, 49, 99306)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 44, 49, 98306)),
        ),
        migrations.AlterField(
            model_name='securityadvice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 44, 49, 99306)),
        ),
    ]
