# Generated by Django 3.0.3 on 2020-03-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0022_createticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
