# Generated by Django 3.0.3 on 2020-04-18 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0025_auto_20200413_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.URLField(blank=True, help_text='URL to a picture of your club (200 characters max)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.URLField(blank=True, help_text='URL to the poster for the event (200 characters max.)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, help_text='Post a picture of your pretty face, dude (200 characters max)', null=True),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 51, 8, 533592)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 51, 8, 533592)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 51, 8, 532604)),
        ),
        migrations.AlterField(
            model_name='securityadvice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 51, 8, 533592)),
        ),
    ]
