# Generated by Django 3.0.3 on 2020-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0025_auto_20200320_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='renew_premium',
            field=models.BooleanField(default=False),
        ),
    ]
