# Generated by Django 3.0.4 on 2020-03-22 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0026_profile_renew_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 19, 5, 28, 966059)),
        ),
        migrations.AddField(
            model_name='qr_item',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
