# Generated by Django 3.0.3 on 2020-04-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0028_auto_20200418_2012'),
        ('clubby', '0028_auto_20200418_2138'),
    ]

    operations = [
    ]
