# Generated by Django 3.0.3 on 2020-03-23 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0028_auto_20200323_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 12, 36, 24, 365489)),
        ),
    ]
