# Generated by Django 3.0.4 on 2020-03-23 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0029_auto_20200323_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='recommended',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('r', 'refreshment'), ('c', 'cocktail'), ('s', 'shot'), ('b', 'beer'), ('w', 'wine'), ('k', 'snack'), ('h', 'hookah'), ('m', 'misc.')], default='m', help_text='product type', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='reservation_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 20, 52, 4, 871497)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 20, 52, 4, 871497)),
        ),
    ]
