# Generated by Django 3.0.3 on 2020-05-05 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0029_merge_20200419_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0, help_text='choose the duration time minutes.'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time_minutes',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0, help_text='choose the start time minutes.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[(11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0, help_text='event duration in hours, max is 11 hours.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('rock', 'rock'), ('pop', 'pop'), ('techno', 'techno'), ('electro', 'electro'), ('hip hop', 'hip hop'), ('trap', 'trap'), ('reggaeton', 'reggaeton'), ('indie', 'indie'), ('metal', 'metal'), ('latin', 'latin'), ('edm', 'edm'), ('cumbia', 'cumbia'), ('rap', 'rap'), ('house', 'house'), ('r&b', 'r&b'), ('latino', 'latino'), ('dance', 'dance'), ('k-pop', 'k-pop'), ('funk', 'funk'), ('folk', 'folk'), ('disco', 'disco'), ('emo', 'emo'), ('country', 'country'), ('trance', 'trance'), ('reggae', 'reggae'), ('salsa', 'salsa'), ('soul', 'soul'), ('jazz', 'jazz'), ('ska', 'ska'), ('dubstep', 'dubstep'), ('rumba', 'rumba'), ('punk', 'punk'), ('ranchera', 'ranchera'), ('grunge', 'grunge'), ('flamenco', 'flamenco'), ('otro', 'otro')], default='pop', help_text='event music type', max_length=100),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 20, 4, 52, 129424)),
        ),
        migrations.AlterField(
            model_name='qr_item',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 20, 4, 52, 129424)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 20, 4, 52, 128425)),
        ),
        migrations.AlterField(
            model_name='securityadvice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 20, 4, 52, 129424)),
        ),
    ]
