# Generated by Django 3.0.5 on 2020-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0031_auto_20200427_1328'),
        ('clubby', '0030_auto_20200505_2004'),
    ]

    operations = [
    ]
