dist: xenial

language: python 
 
python: 
  - 3.6 
services:
  -mysql
install:
  - pip install -r requirements.txt
before_script:
  -mysql -e 'create database test;' -u root
script:
- ls
- cd "Django application"
- cd "project"
- python manage.py test