# Generated by Django 3.0.3 on 2020-03-15 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of your club.', max_length=50)),
                ('address', models.CharField(help_text='Enter the full address so google maps can find it.', max_length=200)),
                ('max_capacity', models.IntegerField(help_text="The capacity of your club, you're responsible for the enforcement of this number.")),
                ('NIF', models.CharField(help_text='Company number for the club', max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.IntegerField(default=12, help_text='event start time 24h format.', max_length=2)),
                ('duration', models.IntegerField(default=12, help_text='event duration in hours, max is 12 hours', max_length=2)),
                ('event_type', models.CharField(blank=True, choices=[('c', 'casual'), ('f', 'fancy'), ('d', 'dress_up'), ('p', 'private')], default='c', help_text='event type', max_length=1)),
                ('atendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubby.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubby.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(default='Basic', help_text='The name of the type of ticket you are trying to sell.', max_length=40)),
                ('description', models.TextField(default='this allows you to enter the party.', help_text='Decribe what this ticket entices.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubby.Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.IntegerField(default=4, help_text='max hours after the event starts people can arrive at.', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubby.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('stars', models.IntegerField(help_text='star rating 1-10')),
                ('recommended', models.BooleanField(help_text='would you recommend this club?')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubby.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QR_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('priv_key', models.CharField(max_length=128)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubby.Product')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubby.Reservation')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubby.Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('funds', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_user', 'Is a user and can do everything an identified user can.'), ('is_owner', 'Is an owner and can do everything an identified owner can.'), ('is_premium_owner', 'Is a premium owner and can do everything an identified owner can and more.')),
            },
        ),
    ]
