# Generated by Django 3.0.3 on 2020-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubby', '0012_auto_20200311_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.IntegerField(default=12, help_text='event start time 24h format.', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
